baseURL = "https://www.ultradordrecht.nl"
title = "Stichting Ultra Dordrecht"
languageCode = "en"
defaultContentLanguage = "nl"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "tailwind"
enableGitInfo = true

[pagination]
  pagerSize = 20

[markup]
  _merge = "deep"

[taxonomies]
category = "categories"
tag = "tags"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
