# SEO keywords and description for your site.
keywords = "dordrecht, willie, batenburg, ultra, muziek, theater, markt"
subtitle = "Culturele activiteit in Dordrecht"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"

jsonLD = true

showReadingTime = false

[author]
  name = "Ultra Dordrecht"
  email = "info@ultradordrecht.nl"

[header]
  logo = "logo.png"

[footer]
  since = 2020
  poweredby = false

# giscus is comments system powered by GitHub Discussions
# generate configurations from https://giscus.app/
[giscus]
  enabled = false

[social_media]
  [[social_media.items]]
    enabled = true
    title = 'Facebook'
    icon = 'brand-facebook'
    link = 'https://www.facebook.com/ultradordrecht'

  [[social_media.items]]
    enabled = false
    title = 'X'
    icon = 'brand-x'
    link = 'https://x.com/'

  [[social_media.items]]
    enabled = true
    title = 'Instagram'
    icon = 'brand-instagram'
    link = 'https://www.instagram.com/ultradordrecht/'

  [[social_media.items]]
    enabled = false
    title = 'LinkedIn'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/'

  [[social_media.items]]
    enabled = false
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/'
